# Generated by Django 5.2 on 2025-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_ledger_closing_balance_alter_ledger_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledger",
            name="closing_balance",
        ),
        migrations.RemoveField(
            model_name="ledger",
            name="created_at",
        ),
        migrations.AddField(
            model_name="ledger",
            name="email",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ledger",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
