# Generated by Django 5.2 on 2025-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_ledger_closing_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="email",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
