# Generated by Django 5.2 on 2025-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_ledger_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
