# Generated by Django 5.1.2 on 2025-05-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_ledger_email_alter_ledger_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="ledger_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("coa", "Chart of Accounts"),
                    ("item", "Item"),
                ],
                default="coa",
                max_length=20,
            ),
        ),
    ]
