# Generated by Django 5.1.2 on 2025-05-23 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_vendor_unique_together_remove_vendor_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ledger",
        ),
    ]
