# Generated by Django 5.1.2 on 2025-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_remove_debtor_user_ledger_delete_creditor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="mailing_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="pincode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
