# Generated by Django 5.1.2 on 2025-05-23 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_ledger_address_ledger_country_ledger_mailing_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledger",
            name="address",
        ),
        migrations.RemoveField(
            model_name="ledger",
            name="country",
        ),
        migrations.RemoveField(
            model_name="ledger",
            name="mailing_name",
        ),
        migrations.RemoveField(
            model_name="ledger",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="ledger",
            name="state",
        ),
    ]
