# Generated by Django 5.1.2 on 2025-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_ledger_address_remove_ledger_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
