# Generated by Django 5.1.2 on 2025-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_ledger_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ledger",
            old_name="phone",
            new_name="ledger_mobile",
        ),
        migrations.AddField(
            model_name="ledger",
            name="country_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="state_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
