# Generated by Django 5.1.2 on 2025-05-24 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_vendor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ledger",
            unique_together={("user", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="vendor",
            unique_together={("user", "name", "parent")},
        ),
    ]
