# Generated by Django 5.2.1 on 2025-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="zoho_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
