# Generated by Django 5.2.1 on 2025-07-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="cgst",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="sgst",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="tax_type",
            field=models.CharField(default="unknown", max_length=50),
        ),
    ]
