# Generated by Django 5.1.2 on 2025-07-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_invoiceitem_cgst_invoiceitem_sgst_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="cgst",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="sgst",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="tax_type",
        ),
        migrations.AddField(
            model_name="item",
            name="gst_applicable",
            field=models.CharField(default="Not Applicable", max_length=50),
        ),
        migrations.AddField(
            model_name="item",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
