# Generated by Django 5.2.4 on 2025-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='zoho_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
