# Generated by Django 5.2.4 on 2025-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_invoice_zoho_invoice_id_delete_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='zoho_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
