# Generated by Django 5.2.4 on 2025-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_ledger_zoho_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='zoho_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
