# Generated by Django 5.2.4 on 2025-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zohotax',
            name='fetched_from_tally',
            field=models.BooleanField(default=False),
        ),
    ]
