# Generated by Django 5.2.4 on 2025-07-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zohotax',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
    ]
