# Generated by Django 5.2.4 on 2025-07-26 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_purchase_purchaseitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('vendor_zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_zoho_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zoho_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fetched_from_tally', models.BooleanField(default=False)),
                ('pushed_to_zoho', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agst_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ledger')),
            ],
            options={
                'unique_together': {('user', 'payment_number')},
            },
        ),
    ]
