# Generated by Django 5.2.4 on 2025-07-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_payment_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
    ]
