# Generated by Django 5.2.4 on 2025-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_purchaseitem_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_ledger',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
