# Generated by Django 5.2.4 on 2025-07-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_purchase_purchase_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agst_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.purchase'),
        ),
    ]
