# Generated by Django 5.2.4 on 2025-07-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='website',
            field=models.CharField(blank=True, null=True),
        ),
    ]
