# Generated by Django 5.2.4 on 2025-07-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_creditnote_creditnoteitem_debitnote_debitnoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.invoice'),
        ),
    ]
