# Generated by Django 5.2.4 on 2025-07-29 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
    ]
