# Generated by Django 5.2.4 on 2025-07-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_expenses_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='agst_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_zoho_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vendor_zoho_id',
        ),
    ]
