# Generated by Django 5.2.4 on 2025-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_journal_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='pushed_to_zoho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='zoho_journal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
