# Generated by Django 5.2.4 on 2025-07-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_journal_pushed_to_zoho_journal_zoho_journal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='agst_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.purchase'),
        ),
    ]
