# Generated by Django 5.2.4 on 2025-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_payment_agst_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zoho_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
