# Generated by Django 5.2.4 on 2025-07-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_creditnote_against_number_debitnote_against_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='against_number',
            new_name='against_ref',
        ),
    ]
