# Generated by Django 5.2.4 on 2025-07-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_rename_against_number_creditnote_against_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='against_number',
            new_name='against_ref',
        ),
    ]
