# Generated by Django 5.2.4 on 2025-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_rename_against_number_debitnote_against_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
