# Generated by Django 5.2.4 on 2025-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_ledger_opening_balance_vendor_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='ledger_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='ledger_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
