# Generated by Django 5.2.4 on 2025-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
