# Generated by Django 5.2.4 on 2025-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_account_from_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
