from django.contrib import admin
from .models import *

admin.site.register(Ledger)
admin.site.register(Vendor)
admin.site.register(Account)
admin.site.register(ZohoBooksCredential)
admin.site.register(Item)
admin.site.register(Invoice)
admin.site.register(InvoiceItem)
admin.site.register(ZohoTax)
admin.site.register(Receipt)
admin.site.register(Purchase)
admin.site.register(PurchaseItem)
admin.site.register(Payment)
admin.site.register(BankAccount)
admin.site.register(DebitNote)
admin.site.register(DebitNoteItem)
admin.site.register(CreditNote)
admin.site.register(CreditNoteItem)
admin.site.register(Expenses)
admin.site.register(Journal)
admin.site.register(JournalEntry)